import os
import subprocess
from pathlib import Path

def main():
    print("🚀 F5-TTS Inference using Voice.ai as reference")
    
    # Text to synthesize
    text = "क्या आप जानते हैं कि आपके पेट में इतना तेज़ाब है जो एक लोहे की कील को भी गला सकता है? जी हाँ, ये है Hydrochloric acid, जिसका pH लेवल 1 से 2 के बीच होता है — ये तेज़ाब इतना खतरनाक है कि ये आपकी चमड़ी को जला सकता है। तो फिर आपका पेट खुद को क्यों नहीं पचाता? दरअसल, आपके पेट की दीवारों पर एक 'Mucus' की मोटी परत होती है। ये layer एक protective shield की तरह काम करती है, जो acid को पेट के tissues तक पहुँचने से पहले ही रोक देती है। अगर ये shield न हो, तो आपका पेट खुद को ही ख़त्म कर देगा! Science के लिए follow करें।"
    
    # Paths
    ref_audio = "public/audio.mp3" # Previously generated by Voice.ai
    model_ckpt = "tts-model/models/hindi_tts_checkpoint.bin"
    vocab_file = "tts-model/models/vocab.txt"
    output_audio = "public/audio_f5.mp3"
    
    # Ensure public dir exists
    Path("public").mkdir(parents=True, exist_ok=True)
    
    # Check if reference exists
    if not os.path.exists(ref_audio):
        print("⚠️ Reference audio missing. Downloading last known good...")
        subprocess.run(["curl", "-L", "-o", ref_audio, "https://share.zapia.com/kx0nx0uuc6dz1bbhr5371i"], check=True)

    print("🎙️ Running F5-TTS Synthesis...")
    
    # We use the F5-TTS CLI for inference
    # Note: Adjusting parameters for high quality
    cmd = [
        "f5-tts_infer-cli",
        "--model_path", model_ckpt,
        "--vocab_path", vocab_file,
        "--ref_audio", ref_audio,
        "--ref_text", "क्या आप जानते हैं", # Short segment of the ref audio text
        "--gen_text", text,
        "--output_dir", "public/",
        "--output_file", "audio.mp3" # Overwrite public/audio.mp3
    ]
    
    try:
        subprocess.run(cmd, check=True)
        print("✅ F5-TTS Synthesis Complete!")
    except subprocess.CalledProcessError as e:
        print(f"❌ Synthesis failed: {e}")
        # Fallback to ref_audio if synthesis fails to not break the render
        print("🔄 Falling back to original audio.")

if __name__ == "__main__":
    main()
